Add example traces (plus typo in README)
ligurio/elle-cli pull request #49
Opened 2022-05-12 20:05 UTC by mprimi

2022-05-13 19:33 UTC, ligurio commented on README.md
> +- `false`     means the history was invalid
Good catch, thanks!

2022-05-16 07:36 UTC, ligurio requested changes

2022-05-16 07:36 UTC, ligurio commented on histories/elle/rwregister-fail.edn
> +; P1 and P2 read X and see NULL
history is valid:

```
sergeyb@pony:~/sources/elle-cli$ java -jar ./target/elle-cli-0.1.3-standalone.jar --model rw-register histories/elle/rwregister-fail.edn --verbose
{"valid?":true}
```

2022-05-16 07:36 UTC, ligurio commented on histories/elle/cas-fail.edn
> +; Two processes read initial value nil
Please add new histories to the `test.sh`.

2022-05-16 07:44 UTC, ligurio requested changes

2022-05-16 07:44 UTC, ligurio commented on histories/elle/cas-fail.edn
> +{:process 1, :type :ok,     :f :read, :value nil}
Good and bad samples for CAS register are already exist, see `histories/knossos/cas-register/`.

2022-05-16 07:44 UTC, ligurio commented on histories/elle/cas-ok.edn
> +; Two processes read initial value nil
Good and bad samples for CAS register are already exist, see `histories/knossos/cas-register/`.

2022-05-16 07:44 UTC, ligurio commented on histories/elle/list-fail.edn
> +; P1 and P2 read x and see an empty list
Bad sample for list-append is already exists, see `histories/elle/list-append-gh-30.edn`.

2022-05-16 07:44 UTC, ligurio commented on histories/elle/list-ok.edn
> +; P1 and P2 read x and see an empty list
"Good" sample is already exist, see `histories/elle/paper-example.edn`.

2022-05-16 07:44 UTC, ligurio commented on histories/elle/rwregister-ok.edn
> +; P1 and P2 read X and see NULL
"Good" sample is already exist, see `histories/elle/rw-register.edn`.

2022-05-16 07:44 UTC, ligurio commented on histories/elle/rwregister-fail.edn
> +{ :process 1, :index 1, :type :invoke, :f :txn :value [[:r x]] }
Please fix a history sample and add it to the `test.sh`.

2022-05-16 21:31 UTC, mprimi commented
I just wanted to share some samples I composed, thinking that more tests/examples are always better. 

Feel free to cherry pick or copy-paste whatever you think is good, if any, and throw away the rest.

2022-05-16 21:31 UTC, closed without merging

2022-05-17 07:15 UTC, ligurio commented
cherry-picked https://github.com/ligurio/elle-cli/commit/7970c5938baefa2669f1dc98bb2a497f008e950b
Thanks!